### ISSUE TITLE
RequirementParseError while installing requirement.

### ISSUE THREAD

**Issue by yzmyyff** [matthewfl/nlp-entity-convnet#1]
OS: Ubuntu Server 16.04
Python version: 2.7.11
Error log:

``` python
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 305, in run
    wheel_cache
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 289, in populate_requirement_set
    wheel_cache=wheel_cache):
  File "/usr/lib/python2.7/dist-packages/pip/req/req_file.py", line 93, in parse_requirements
    for req in req_iter:
  File "/usr/lib/python2.7/dist-packages/pip/req/req_file.py", line 158, in process_line
    isolated=isolated, options=req_options, wheel_cache=wheel_cache
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 234, in from_line
    extras).extras
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2833, in parse
    req, = parse_requirements(s)
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2781, in parse_requirements
    yield Requirement(line)
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2790, in __init__
    raise RequirementParseError(str(e))
RequirementParseError: Invalid requirement, parse error at "u'__placeh'"
```

seems that couldn't install the dependencies.

**Comment by yzmyyff** [comment]
Sorry to report it.
I solved the problem after upgrade related pip.
Thanks for your good work.
