### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: java.io.EOFException: Unexpected end of ZLIB input stream

### ISSUE THREAD

**Issue by bian2015** [matthewfl/nlp-entity-convnet#3]
hi,matthewfl 
when I run 
    ./demo.sh

there was an exception :

Location: rec.parks.theme_20050217.2019 (part 0), sentence 17: (9, 14) ArrayBuffer(carousel, artwork, collector, and, printer)
WARNING: multiple gold coref chunks matching span
Location: rec.parks.theme_20050217.2019 (part 0), sentence 17: (9, 14) ArrayBuffer(carousel, artwork, collector, and, printer)
Extracted 112117 queries from 599 documents
Exception in thread "main" java.lang.RuntimeException: java.io.EOFException: Unexpected end of ZLIB input stream
    at edu.berkeley.nlp.entity.GUtil$.loadGz(GUtil.scala:83)
    at edu.berkeley.nlp.entity.GUtil$.load(GUtil.scala:37)
    at edu.berkeley.nlp.entity.wiki.WikipediaInterface$.main(WikipediaInterface.scala:315)
    at edu.berkeley.nlp.entity.wiki.WikipediaInterface.main(WikipediaInterface.scala)
Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
    at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
    at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
    at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
    at java.io.ObjectInputStream$PeekInputStream.read(ObjectInputStream.java:2338)
    at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2351)

how can  I solve this mistake ？

**Comment by matthewfl** [comment]
Exception in thread "main" java.lang.RuntimeException: java.io.EOFException: Unexpected end of ZLIB input stream

It looks like something didn't get fully downloaded or was interrupted in an earlier phase of generating some file.  Maybe try deleting the wikipedia interface and starting it again.  Otherwise I would just delete all the generated and downloaded files and rerun the demo script
