### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by bian2015** [matthewfl/nlp-entity-convnet#6]
[jack@localhost nlp-entity-convnet]$ python runner.py --queries ./data/ace-dev-set-queries.json --surface_count ./data/enwiki-vecs-surface.json --wordvecs ./data/enwiki-vecs.bin --redirects ./data/enwiki-vecs-redir.json --wiki_dump ./data/enwiki-latest-pages-articles.xml --raw_output ./data/ace-dev-set.h5 --csv_output ./data/ace-dev-set.csv
Using gpu device 0: Tesla K40m (CNMeM is disabled, cuDNN 4007)
Total queries possible: 0.99582929195, Testing queries possible: 0.986433191355
Number word vectors: 2293957
Finding relevant pages from wikipedia
Loading model
ERROR (theano.gof.opt): Optimization failure due to: local_avgpool_dnn_grad_stride
ERROR (theano.gof.opt): node: AveragePoolGrad{ds=(5, 1), ignore_border=True, st=(5, 1), padding=(0, 0), mode='sum'}(HostFromGpu.0, Reshape{4}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/usr/lib64/python2.7/site-packages/theano/sandbox/cuda/dnn.py", line 2507, in local_avgpool_dnn_grad_stride
    ret = GpuDnnPoolGrad(mode=mode)(gpu_contiguous(inp),
  File "/usr/lib64/python2.7/site-packages/theano/sandbox/cuda/dnn.py", line 1710, in **init**
    assert mode in ('max', 'average_inc_pad', 'average_exc_pad')
AssertionError

Traceback (most recent call last):
  File "runner.py", line 306, in <module>
    main()
  File "runner.py", line 241, in main
    queries_exp = **import**(args.exp_model).queries_exp
  File "/home/disk1/luojianbo/deep_nlp/nlp-entity-convnet/exp_multi_conv_cosim.py", line 923, in <module>
    queries_exp = EntityVectorLinkExp()
  File "/home/disk1/luojianbo/deep_nlp/nlp-entity-convnet/exp_multi_conv_cosim.py", line 51, in **init**
    self._setup()
  File "/home/disk1/luojianbo/deep_nlp/nlp-entity-convnet/exp_multi_conv_cosim.py", line 543, in _setup
    on_unused_input='ignore',
  File "/usr/lib64/python2.7/site-packages/theano/compile/function.py", line 320, in function
    output_keys=output_keys)
  File "/usr/lib64/python2.7/site-packages/theano/compile/pfunc.py", line 479, in pfunc
    output_keys=output_keys)
  File "/usr/lib64/python2.7/site-packages/theano/compile/function_module.py", line 1776, in orig_function
    output_keys=output_keys).create(
  File "/usr/lib64/python2.7/site-packages/theano/compile/function_module.py", line 1456, in __init__
    optimizer_profile = optimizer(fgraph)
  File "/usr/lib64/python2.7/site-packages/theano/gof/opt.py", line 101, in **call**
    return self.optimize(fgraph)
  File "/usr/lib64/python2.7/site-packages/theano/gof/opt.py", line 89, in optimize
    ret = self.apply(fgraph, _args, *_kwargs)
  File "/usr/lib64/python2.7/site-packages/theano/gof/opt.py", line 230, in apply
    sub_prof = optimizer.optimize(fgraph)

**Comment by matthewfl** [comment]
this work was not run on cuda, it appears that there is some compile time difference.

you could uninstall cuda or lookup how to disable it with theano.

**Comment by bian2015** [comment]
thx,I have run demo.sh ！
But I am very confused about the training data format, I do not have the conll format data, then how to use the wiki text to do the training samples,  it must be converted to ACE or CONLL format  anyway ？

**Comment by matthewfl** [comment]
The system requires that the data is in the conll format.  There are some commands that you can use to preprocess data.  You will have to modify it to work with the format your data is in currently.

Start by looking here: https://github.com/matthewfl/berkeley-entity/blob/release/src/main/java/edu/berkeley/nlp/entity/preprocess/PreprocessingDriver.java#L100-L145
