### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by LMY-nlp0701** [matthewfl/nlp-entity-convnet#7]
Number word vectors:4845776
Finding relevant pages from wikipedia
Loading model
Traceback (most recent call last):
  File "runner.py", line 307, in <module>
    main()
  File "runner.py", line 242, in main
    queries_exp = __import__(args.exp_model).queries_exp
  File "/home/hlxu/MYLi/nlp-entity-convnet-master/exp_multi_conv_cosim.py", line 923, in <module>
    queries_exp = EntityVectorLinkExp()
  File "/home/hlxu/MYLi/nlp-entity-convnet-master/exp_multi_conv_cosim.py", line 51, in __init__
    self._setup()
  File "/home/hlxu/MYLi/nlp-entity-convnet-master/exp_multi_conv_cosim.py", line 543, in _setup
    on_unused_input='ignore',
  File "/home/hlxu/.local/lib/python2.7/site-packages/theano/compile/function.py", line 317, in function
    output_keys=output_keys)
  File "/home/hlxu/.local/lib/python2.7/site-packages/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/home/hlxu/.local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "/home/hlxu/.local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/home/hlxu/.local/lib/python2.7/site-packages/theano/gof/link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "/home/hlxu/.local/lib/python2.7/site-packages/theano/gof/vm.py", line 1091, in make_all
    impl=impl))
  File "/home/hlxu/.local/lib/python2.7/site-packages/theano/gof/op.py", line 955, in make_thunk
    no_recycling)
  File "/home/hlxu/.local/lib/python2.7/site-packages/theano/gof/op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "/home/hlxu/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)
  File "/home/hlxu/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1157, in __compile__
    keep_lock=keep_lock)
  File "/home/hlxu/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1620, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/home/hlxu/.local/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1181, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/home/hlxu/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1523, in compile_cmodule
    preargs=preargs)
  File "/home/hlxu/.local/lib/python2.7/site-packages/theano/gof/cmodule.py", line 2397, in compile_str
    return dlimport(lib_filename)
  File "/home/hlxu/.local/lib/python2.7/site-packages/theano/gof/cmodule.py", line 309, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: ('The following error happened while compiling the node', BatchedDot(Reshape{2}.0, AdvancedSubtensor1.0), '\n', '/home/hlxu/.theano/compiledir_Linux-3.10-el7.x86_64-x86_64-with-centos-7.2.1511-Core-x86_64-2.7.5-64/tmpVaEO5Z/cdbcc01d8173663c5f7eb751ea59d017085373e926d65bd54e712608045cc6a6.so: undefined symbol: dgemm_', '[BatchedDot(<TensorType(float32, matrix)>, <TensorType(float32, matrix)>)]')

**Comment by LMY-nlp0701** [comment]
I have solved this problem.
The version of Theano is 0.8.0 and Lasagna is 0.2
